
from enum import Enum


class ConstantesPosiciones(Enum):
    XVERBO = 800
    YVERBO = 50
    ACTUALIZACION_X = 200
    ACTUALIZACION_Y = 200
    ANGULO_APERTURA_INICIAL = 200
    APERTURA_NODO_VERBO_EJE_X = 200
    APERTURA_NODO_VERBO_EJE_Y = 60