
from enum import Enum


class ConstantesPosiciones(Enum):
    XVERBO = 800
    YVERBO = 50
    ACTUALIZACION_X = 200
    ACTUALIZACION_Y = 200
    ANGULO_APERTURA_INICIAL = 250
    ANGULO_APERTURA_LADO_IZQUIERDO = 0
    ANGULO_APERTURA_LADO_DERECHO  = 150
    ANGULO_APERTURA_LADO_ARRIBA = 70
    ANGULO_APERTURA_LADO_ABAJO = 250
    APERTURA_NODO_VERBO_EJE_X = 200
    APERTURA_NODO_VERBO_EJE_Y = 60